### ISSUE TITLE
Docker-compose up error: resulting devices cgroup doesn't match target mode: unknown

### ISSUE THREAD

**Issue by fdbatista** [carlosvin/docker-reverse-proxy-multi-domain#1]
Hi @carlosvin

I am trying to run the example, but I get the following output from docker-compose up:

#
ERROR: for docker-reverse-proxy-multi-domain_nginx-proxy_1  Cannot start service nginx-proxy: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: resultingStarting docker-reverse-proxy-multi-domain_b_1           ... done

ERROR: for nginx-proxy  Cannot start service nginx-proxy: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: resulting devices cgroup doesn't match target mode: unknown
#

This is the configuration I am trying on VPS:

*docker-compose.yaml*

```yml
a:
  build: a
  environment:
    VIRTUAL_HOST: a.criptoconversor.tech
  restart: always

b:
  build: b
  environment:
    VIRTUAL_HOST:  b.criptoconversor.tech
  restart: always

nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

  restart: always
  privileged: true
```
*/etc/hosts*
```bash
127.0.0.1	a.criptoconversor.tech
127.0.0.1	b.criptoconversor.tech
```
Dockerfiles in `a` and `b` folder were not edited.

Any idea why this might be happening?

I get the same error in my laptop as well, using my hostname instead of the production domain name.

Thanx.
